### ISSUE TITLE
 LocalCUDACluster() not working on python script mode

### ISSUE THREAD

**Issue by MikeChenfu** [mrocklin/dask-cuda#5]
Hello, I would like to try some examples on multiple GPUs. Everything is good in python interactive mode, but got errors in script mode. Here is the error. I really appreciate for any suggestions.

```
Traceback (most recent call last):
  File "/conda/lib/python3.7/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "/conda/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/conda/lib/python3.7/site-packages/distributed/deploy/local.py", line 220, in _start_worker
    yield w._start()
  File "/conda/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/conda/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/conda/lib/python3.7/site-packages/distributed/nanny.py", line 158, in _start
    response = yield self.instantiate()
  File "/conda/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/conda/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/conda/lib/python3.7/site-packages/distributed/nanny.py", line 228, in instantiate
    self.process.start()
  File "/conda/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/conda/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/conda/lib/python3.7/site-packages/distributed/nanny.py", line 375, in start
    yield self.process.start()
  File "/conda/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/conda/lib/python3.7/site-packages/distributed/process.py", line 35, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/conda/lib/python3.7/site-packages/distributed/process.py", line 184, in _start
    process.start()
  File "/conda/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/conda/lib/python3.7/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File "/conda/lib/python3.7/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "/conda/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/conda/lib/python3.7/multiprocessing/popen_forkserver.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/conda/lib/python3.7/multiprocessing/spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "/conda/lib/python3.7/multiprocessing/spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by jakirkham** [comment]
Are you starting the cluster within the `if __name__ == '__main__':` block? Also please see [the note in this doc section]( http://distributed.dask.org/en/latest/local-cluster.html#local-cluster ).

**Comment by MikeChenfu** [comment]
Thanks, problem solved!
